# Generated by Django 3.2.9 on 2021-12-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imbd_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('year', models.CharField(blank=True, max_length=25)),
                ('Runtime', models.CharField(blank=True, max_length=25)),
                ('Rated', models.CharField(blank=True, max_length=10)),
                ('Released', models.CharField(blank=True, max_length=25)),
                ('Poster', models.ImageField(blank=True, upload_to='movies')),
            ],
        ),
    ]
