# Generated by Django 3.2.9 on 2021-12-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_alter_list_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Rated',
            new_name='Rating',
        ),
        migrations.AddField(
            model_name='movie',
            name='Awards',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='movie',
            name='Directors',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='Genres',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='Plot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='Stars',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movie',
            name='Trailer',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
