# Generated by Django 3.2.9 on 2021-12-07 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_lists'),
        ('movie', '0004_auto_20211206_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
        ),
    ]
