# Generated by Django 3.2.9 on 2021-12-07 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_lists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lists',
        ),
    ]
